### ISSUE TITLE
Slow Rundeck start

### ISSUE THREAD

**Issue by makered** [rundeck/rundeck#1685]
I have a v2.6.2 cluster with two nodes sharing a database and using S3 for logs (plugin). Multiple jobs are scheduled and execution history is into the thousands now.

Recently after restarting the rundeckd service on both nodes, one node became available after a few minutes, while the second seems to be taking an excessive amount of time to come online. Looking at service.log on the affected node shows a growing list of entries similar to:

```
INFO  LogFileStorageService: re-queueing incomplete log storage request for execution 182777
```

Apparently this is some form of a cleanup process that needs to complete before the service comes online but I am unable to find much information on it. 

Any thoughts as to what this may be attributed to and why only one of the two nodes seems to be affected?

Thanks

**Comment by makered** [comment]
After some poking around my assumption as to why only one node is stuck re-queueing thousands of log storage requests and blocking UI from launching is that those requests are associated with the node due to scheduled job affinity based on cluster ID. 

I am still puzzled however as to how I ended up with so many log storage requests that are not in completed state (100k/354k in log_file_storage_request table). Will cleaning execution history via UI or API call remove associated log_file_storage_request entries?

**Comment by gschueler** [comment]
is there anything in your previous logs about why the storage request failed?

i will verify whether removing execution history will clean out those request entries

it also seems like startup should not be slow simply due to a backlog of storage requests...that sounds like a bug

**Comment by gschueler** [comment]
@makered yes, removing executions (e.g. via bulk delete) will remove log_file_storage request entries for them

**Comment by makered** [comment]
Thanks for confirming bulk deletes @gschueler. 

From my observation resumeIncompleteLogStorage() is ran on startup and although the server is already  processing scheduled jobs, UI is unavailable until re-queueing is complete (no listening socket per netstat)

Nothing specific in the logs, I may need to enable more debugging. We are using the S3 plugin to send logs to S3 and I noticed for failed log storage requests there are still log files on the local filesystem (/var/lib/rundeck/logs/rundeck/<job name>/...). Perhaps the S3 plugin can't keep up.

**Comment by subirbp** [comment]
@gschueler @makered I am facing the same issue at the moment. How did you manage to remove executions (e.g. via bulk delete) in order to remove log_file_storage request entries? I'm getting "grails.app.services.rundeck.services.LogFileStorageService - re-queueing incomplete log storage request for execution 589". 

And I'm also not being able to access the UI. Please suggest.

Thanks,
Subir

**Comment by makered** [comment]
@subirbp Incomplete log storage request issue was addressed in 2.6.6 (https://github.com/rundeck/rundeck/issues/1719) I believe.

We scheduled a Rundeck job that kicks off a Python script nightly to go though projects/jobs and purge old executions. I am planning on open-sourcing the script, just need to get company approval first.

**Comment by subirbp** [comment]
@makered Thanks for the prompt response. I'm still getting the following error for the past several hours:

INFO  grails.app.services.rundeck.services.LogFileStorageService - re-queueing incomplete log storage request for execution 37059

and when I try $ curl localhost:4440/user/login, I'm still getting curl: (7) Failed to connect to localhost port 4440: Connection refused

Therefore I'm not being able to access the UI. I'm seeing some of the jobs running in the logs, but not sure at the moment how to end those re-queueing messages, and access the UI.

Is version upgrade of rundeck the only way forward in order to solve this?

**Comment by danifr** [comment]
I wrote something a white ago for this. You can check it out

https://github.com/danifr/rundeck-scripts/blob/master/py_scripts/deleteoldlogs.py

**Comment by gschueler** [comment]
@subirbp we added a new configuration flag to address the slow startup in version 2.6.5.  The default is to requeue the old log storage request asynchronously to avoid delay at startup.  We also added GUI support for managing the backlog.

https://github.com/rundeck/rundeck/issues/1771

**Comment by subirbp** [comment]
@gschueler thanks for the information. I'll try out the latest version 2.6.7.
