### ISSUE TITLE
Logs in Node View are broken since 3.3.0

### ISSUE THREAD

**Issue by vonBork** [rundeck/rundeck#6292]
**Describe the bug**
Running Jobs in parallel Mode. Trying to view logs from one step. In rundeck versions previous to 3.3.0 you could open the logoutput from one Step( see screenshot). But now the loading spinner won't stop and the logs arren't loaded.

I prefere view logs in the node view to the logoutput view, as the logoutput view can be confusing in parallel mode.

I assume it has something to do with the new logviewer introduced in Version 3.3.0. https://docs.rundeck.com/docs/history/3_3_x/version-3.3.0.html#new-log-viewer

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: rpm
* OS Name/version: CentOS Linux release 7.8

**To Reproduce**
1. Run a Job.
2. Switch to Node View, if needed.
3. Select a host and click on the arrow button in front of it, to show the steps.
4. Select a step and click on the arrow button int front of it, to show it's logs.
5. The loading spinner won't stop and the logs aren't loaded.

**Expected behavior**
Logs of a specified step are loaded.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36640531/88077446-933ebe00-cb7b-11ea-9942-a39f784d9a7a.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Firefox (78.0.2), Chrome (84.0.4147.89)
 - But im quite sure it has nothing to do with the browser or its version.

**Comment by MegaDrive68k** [comment]
Happening on 3.3.0:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/88191727-be6fee80-cc09-11ea-917b-19b1518ebf23.png)

But is fixed on 3.3.1-SNAPSHOT:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/88191730-bf088500-cc09-11ea-990e-dae06a561997.png)

Thanks for your feedback @vonBork!

**Comment by ProTip** [comment]
I'm not sure why this would work in `SNAPSHOT` ATM, haven't merged the fix 😂

**Comment by tungstenostrich** [comment]
I'm still having the issue with version 3.3.1 (3.3.1-20200727).

![image](https://user-images.githubusercontent.com/7681519/90374061-2e3f9080-e073-11ea-96fb-d3bdcff8c897.png)

I'm having a similar phenomenon when listing the installed plugins.

![image](https://user-images.githubusercontent.com/7681519/90375875-da827680-e075-11ea-903d-7e55e43e16c4.png)

**Comment by tungstenostrich** [comment]
I found the problem. I'm behind a reverse proxy and did not set `-Drundeck.jetty.connector.forwarded=true` . Once this parameter was set both, the job output and installed plugin list, are properly shown.
