### ISSUE TITLE
Rendering issues in Internet Explorer 11

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#926]
My company is doing a pilot rollout of IE11. The caveat here is that being a corporate image with Active Directory group policies and all that Fun Stuff, there may well be IE settings I can't control. If these issues are simply due to IE settings then I can present a listing of the necessary settings for IT to craft a policy to be applied to our RD servers. I've attached screenshots of the main dashboard, and the per-project Jobs, Nodes, Commands, and Activity tabs.

![rd-ie11-activity](https://cloud.githubusercontent.com/assets/4806823/4253972/2a0559ce-3aa6-11e4-94af-8452e283e13b.png)
![rd-ie11-commands-](https://cloud.githubusercontent.com/assets/4806823/4253971/2a029afe-3aa6-11e4-95b6-f0ef5e0a8aa8.png)
![rd-ie11-jobs](https://cloud.githubusercontent.com/assets/4806823/4253974/2a05dfa2-3aa6-11e4-9fa4-096cc0d2a022.png)
![rd-ie11-main](https://cloud.githubusercontent.com/assets/4806823/4253975/2a0a1e78-3aa6-11e4-9152-d07f12a754af.png)
![rd-ie11-nodes](https://cloud.githubusercontent.com/assets/4806823/4253973/2a05c576-3aa6-11e4-9918-26d26e16aef1.png)

**Comment by niphlod** [comment]
this should be fixed by https://github.com/rundeck/rundeck/commit/af8f1d31237027364d17ffaa2543f316ccc11e24

**Comment by brunlea** [comment]
The above fix has not worked as the rendering still does not detect the correct version of Internet Explorer that is being used.

**Comment by gschueler** [comment]
fyi: I tested using modern.ie vm, Win7+IE11, and rendering appears correct to me with latest code.

**Comment by pixdrift** [comment]
I am using 2.9.2 with IE11 on Win7 and there are some minor rendering issues when executing jobs. The progress bar doesn't appear to update and the job often requires a browser refresh to update its display from running to succeeded.

Trying to narrow down if this is an IE11 issue, is anyone else experiencing this?

**Comment by gschueler** [comment]
@pixdrift do you have any errors in the javascript console?

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
