### ISSUE TITLE
Incorrect latest version being shown in pop up

### ISSUE THREAD

**Issue by padraiglennon** [rundeck/rundeck#9318]
**Describe the bug**
When clicking on the Rundeck button on the bottom left hand side an incorrect value (in this case older) is being given for the latest version 

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.10] 5.5.0
* install type: [choose: rpm,deb,war,docker] rpm
* OS Name/version: [e.g. ubuntu 20.04] Centos8
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ] Postgres

**To Reproduce**
1. Click to the button at the bottom left hand side of the screen (when logged in)
2. See error

**Expected behavior**
In this example 5.5.0 is installed but v5.0.1 being shown as the latest version

**Screenshots**
![image](https://github.com/user-attachments/assets/325aaae1-b3b9-4e77-9b1f-3d5f27ed1bdd)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] Version 127.0.6533.122

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @padraiglennon 

It seems fixed now, could you confirm on your end?

<img width="688" alt="Screenshot 2024-08-27 at 07 57 18" src="https://github.com/user-attachments/assets/cdc5e97f-3948-4350-884d-d92cc5b5899b">

**Comment by padraiglennon** [comment]
I cleared all browser caches. Still shows the same after logging in again

**Comment by MegaDrive68k** [comment]
Please open a new ticket if it still occurs. Thanks!
